### ISSUE TITLE
Missing if __name__ == "__main__": on regression_ou_composed.py

### ISSUE THREAD

**Issue by DanielCoelho112** [miguelriemoliveira/OptimizationUtils#60]
Hi @miguelriemoliveira,

The script https://github.com/miguelriemoliveira/OptimizationUtils/blob/28ffc9e67308ddd1571363fced69f3b11238c74f/test/workshop2021/regression_ou_composed.py is missing this code:

```python
if __name__ == "__main__":
    main()
```
Do you want me to change?

**Comment by miguelriemoliveira** [comment]
Yes, please do.

**Comment by DanielCoelho112** [comment]
Done
