### ISSUE TITLE
Is there a way to introduce constraints to the optimization?

### ISSUE THREAD

**Issue by DanielCoelho112** [miguelriemoliveira/OptimizationUtils#62]
Hi @miguelriemoliveira and @tiagomfmadeira,

In order to guarantee that the polynomial regression is monotonically increasing in a certain domain (#61 ), I was thinking about introducing one constraint to the optimization, something like this:

`f(x)' >= 0 ∀ x ∈ [0,255]} `

I think this is possible using some optimization libraries, but using scipy.optimize.least_squares I don't know if it is possible.
Have you explored this issue?

**Comment by miguelriemoliveira** [comment]
Hi,

I don't think its possible.

But you could design a function like

f(x) = f(x-1) + a

Where a is always positive ...
