### ISSUE TITLE
Prroblem with OptimizationUtil installation 

### ISSUE THREAD

**Issue by Analtino2021** [miguelriemoliveira/OptimizationUtils#63]
estou a ter um problema com a instalação do optimizationUtils, alguém mais teve este problema ou conseguiu resolver

@manuelgitgomes 
![instaloptimization ](https://user-images.githubusercontent.com/92738054/142724324-7f99b56e-229e-4988-8e56-86d5b1dde74d.png)

**Comment by miguelriemoliveira** [comment]
I do not use the optimization utils install like that. Perhaps @lucasrdalcol or @tiagomfmadeira can help?

**Comment by tiagomfmadeira** [comment]
You should launch pip install from the parent directory of the repo. 
`cd ~/Desktop/psr`
`pip install OptimizationUtils`
Or simply use the full path.
`pip install ~/Desktop/psr/OptimizationUtils`

**Comment by Analtino2021** [comment]
Thanks it worked with 

pip install ~/Desktop/psr/OptimizationUtils
