### ISSUE TITLE
Problem open Bag file

### ISSUE THREAD

**Issue by Analtino2021** [miguelriemoliveira/OptimizationUtils#66]
Iḿ having problem open the Bag file we saved in the last meeting. evry time gives me empty
@miguelriemoliveira  @manuelgitgomes 
```python
    bag = rosbag.Bag('simplebot_2021-11-26-15-13-59.bag')

    for topic, msg, t in bag.read_messages(topics=['Left_scan', 'right_scan']):
       print(msg)

       dictionary.update({"message": message_converter.convert_ros_message_to_dictionary(msg)})
       # json_str = json_message_converter.convert_ros_message_to_json
    bag.close()
    print(dictionary
```
![teste](https://user-images.githubusercontent.com/92738054/143768565-b6900e29-139b-4aa3-9284-4746196096e9.png)

**Comment by miguelriemoliveira** [comment]
Hi @Analtino2021 ,

Please post the result of 

`rosbag info <bag file name>`

I think you will see that you have the wrong topic names...
